# Generated by Django 4.2.3 on 2023-07-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_place_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='disc',
            field=models.TextField(null=True),
        ),
    ]
